print (" v1 ")
v1 = int ( input () ) 
print (" t1 ")
t1 = int ( input () )
print (" v2 ")
v2 = int ( input () ) 
print (" t2 ")
t2 = int ( input () )
print (( v1 * t1 ) + (v2 * t2 ) / ( v1 + v2 ))
