print (" Enter UAH ")
a = int ( input () )
b = int ( 24.4 )
print ( " UAH --> USD " )
print ( a / b )
print ( " USD -->  UAH " )
print ( a * b )
print ( " UAH --> EUR ")
print ( a / 28.5 )
print ( " EUR --> UAH ")
print ( a * 28.5 )
