print ( " enter your total question" )
a = int ( input () )
print ( " enter your correct answers " )
b = int ( input () )
print ( "your_procent_of_correct_answers , %  " ) 
print (  ( b * 100 ) / a  )
